GET http://localhost:3002/corrective
###
GET http://localhost:3002/corrective/0001209
###
POST http://localhost:3003/user/login
Content-Type: application/json

{
    "username": "TKENT",
    "password": "asd"
}
###

POST http://localhost:3003/user/login
Content-Type: application/json

{
    "username": "TKENT",
    "password": "$2b$10$lwOzJ"
}

###
GET http://localhost:3003/csr/nextId

###
GET http://localhost:3003/input/nextId
